version: '3.7'
services:
  ballmate:
    container_name: normal
    build: .
    ports:
      - 8000:8000
    environment:
      - server.profile=dev
      - TZ=Asia/Seoul
      - db.url=jdbc:mysql://master/normal
      - db.username=juno
      - db.password=password
networks:
  default:
    external:
      name: normal